# Generated by Django 2.0 on 2018-01-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200, verbose_name='访问的url')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('hide', models.BooleanField(default=True, verbose_name='是否隐藏')),
                ('style', models.TextField(default='', verbose_name='补充样式，css')),
                ('config', models.CharField(blank=True, max_length=200, verbose_name='配置')),
                ('content', models.TextField(help_text='必须为Markdown格式，参考:https://remarkjs.com/', verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slide',
            },
        ),
    ]
