# Generated by Django 2.0 on 2018-01-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='alias',
            field=models.CharField(max_length=200, unique=True, verbose_name='访问的url'),
        ),
    ]
