# Generated by Django 2.0.1 on 2018-01-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0002_auto_20180110_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='style',
            field=models.TextField(blank=True, verbose_name='补充样式，css'),
        ),
    ]
